### PR TITLE
Add editor config

### PR DESCRIPTION
**Pull request by sippsolutions**
Add editor config

### CODE REVIEW

**Comment by kptdobe** [comment]
@sippsolutions Why are you trying to patch the aem-boilerplate ?

**Comment by sippsolutions** [comment]
@kptdobe because in my opinion a `.editorconfig` is missing that should be equivalent in all projects.
I intentionally wanted to improve the boilerplate :) Can you reopen the PR?

**Comment by kptdobe** [comment]
`.editorconfig` is a VS Code specific config file which has nothing to do with the boilerplate code repo.
What about other IDE specific config files that other dev might be using ? It would quickly be the mess.

**Review by kptdobe — APPROVED** [review]

**Comment by kptdobe** [comment]
ok, thanks. I thought `linting` would be enough but since it requires a `npm install` first, I have seen so many projects where linting is not respected and fails. Let see if `.editorconfig` helps.

**Pull request merged**
