### PR TITLE
Protect authors from invalid definitions.

### LINKED ISSUE #230: Invalid

### PR DESCRIPTION
**Pull request by bstopp**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #230 

Test URLs:
- Before: https://main--franklin-demo--bstopp.hlx.page/
- After: https://bug-section-style-metadata--franklin-demo--bstopp.hlx.page/

### CODE REVIEW

**Comment by davidnuescheler** [comment]
i think while we are at it we could also use something `.classList.add(...styles.filter(style => style))` which would improve on the .forEach(), and would keep the text transformation line (which is already a bit unreadable).

**Comment by bstopp** [comment]
What about something like?

```
const styles = meta.style.split(',')
  .filter((style) => style.trim())
  .map((style) => toClassName(style));
styles.forEach((style) => section.classList.add(style));
```

**Comment by bstopp** [comment]
What about?

```
          const styles = meta.style.split(',')
            .filter((style) => style.trim())
            .map((style) => toClassName(style.trim()));
          section.classList.add(...styles);
```

**Comment by kptdobe** [comment]
@bstopp Closing this PR. This seems to be an important fix, could you bring it to https://github.com/adobe/aem-lib (+tests). Thanks a lot.

**Comment by bstopp** [comment]
Moved to AEM Lib

**Pull request closed without merging**
